on:
  [push, pull_request]

name: CI

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
    - name: Checkout
      uses: actions/checkout@v1.0.0
    - name: Install
      run: |
        npm ci
    - name: Test
      run: |
        npm t
